server:
  port: 8070

spring:
  application:
    name: messaging
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
      bindings:
        msa-poc-input:
          destination: communication-messaging-topic